---
- name: Install Dependent Ubuntu Packages
  ansible.builtin.apt:
    name: policycoreutils # Used by install script to restore SELinux context

- name: If ufw enabled, open api port
  community.general.ufw:
    rule: allow
    port: '{{ api_port }}'
    proto: tcp

- name: If ufw enabled, open etcd ports
    - groups[server_group] | length > 1
  community.general.ufw:
    rule: allow
    port: '2379:2381'
    proto: tcp

- name: If ufw enabled, allow default CIDRs
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - '{{ cluster_cidr }}'
    - '{{ service_cidr }}'
# TODO: not relevant yet
# - name: Setup extra manifests
#   when: extra_manifests is defined
#   block:
#     - name: Make manifests directory
#       ansible.builtin.file:
#         path: '/var/lib/rancher/k3s/server/manifests'
#         mode: '0700'
#         state: directory
#     - name: Copy manifests
#       ansible.builtin.copy:
#         src: '{{ item }}'
#         dest: '/var/lib/rancher/k3s/server/manifests'
#         mode: '0600'
#       loop: '{{ extra_manifests }}'

# - name: Setup optional private registry configuration
#   when: registries_config_yaml is defined
#   block:
#     - name: Make k3s config directory
#       ansible.builtin.file:
#         path: '/etc/rancher/k3s'
#         mode: '0755'
#         state: directory
#     - name: Copy config values
#       ansible.builtin.copy:
#         content: '{{ registries_config_yaml }}'
#         dest: '/etc/rancher/k3s/registries.yaml'
#         mode: '0644'
