- name: Install nvm if not present
  block:
    - name: Download nvm install script
      ansible.builtin.get_url:
        url: '{{ nvm_install_script_url }}'
        dest: /tmp/nvm_install.sh
        mode: '0755'

    - name: Run nvm install script
      ansible.builtin.shell: /tmp/nvm_install.sh
      args:
        executable: /bin/bash
        creates: '{{ userhome }}/.nvm/nvm.sh'
      environment:
        HOME: '{{ userhome }}'
        USER: '{{ username }}'
        NVM_DIR: '{{ userhome }}/.nvm'

    - name: Fix NVM directory ownership
      ansible.builtin.file:
        path: '{{ userhome }}/.nvm'
        owner: '{{ username }}'
        group: '{{ username }}'
        recurse: true
        state: directory
