---
- name: activate docker
  block:
    - name: Activate docker group for current session
      shell: 'newgrp {{ docker_group_name }}'
      become: true
      become_user: '{{ username }}'
      ignore_errors: true

    - name: Inform user about group activation
      debug:
        msg: |
          User {{ username }} has been added to the docker group!

          For your terminal sessions, please either:
          1. Log out and log back in (permanent solution)
          2. Run: newgrp docker (current session only)
          3. Start a new SSH/terminal session

          After activation, test with: docker run hello-world
