---
- name: Download and set permissions for kubectl GPG key
  ansible.builtin.get_url:
    url: '{{ kubectl_gpg_key_url }}'
    dest: '{{ kubectl_keyring_path }}'
    mode: '0644'

- name: Add kubectl repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by={{ kubectl_keyring_path }}] {{ kubectl_repo_url }} /'
    filename: kubernetes

- name: Update apt cache and upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install essential packages
  ansible.builtin.apt:
    state: present
    name: '{{ kubectl_packages }}'
