---
- name: Update apt cache and upgrade system
  tags: git
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install essential packages
  tags: git
  apt:
    state: present
    name:
      - git

- name: Set git user.name
  tags: git
  community.general.git_config:
    name: user.name
    value: '{{ git_user_name }}'
    scope: global

- name: Set git user.email
  tags: git
  community.general.git_config:
    name: user.email
    value: '{{ git_email }}'
    scope: global
