---
- name: Install APT package on localhost
  hosts: localhost
  become: true

  vars_prompt:
    - name: git_email
      prompt: 'Enter your Git email'
      private: false

  vars:
    username: '{{ ansible_env.SUDO_USER | default(ansible_user_id) }}'
    userhome: "{{ '/root' if username == 'root' else '/home/' + username }}"
    fonts_dir: '{{ userhome }}/.local/share/fonts'

  roles:
    - docker
    - git
    - kubectl
    - nvm
    - ssh
    - zsh

  handlers:
    - name: Display setup summary
      debug:
        msg: |
          Setup completed successfully!
          User: {{ username }}
          Home: {{ userhome }}
          Fonts installed in: {{ fonts_dir }}

  tasks:
    - name: Install essential packages
      apt:
        state: present
        name:
          - vim
          - python3-pip
          - tree

    - name: Install snap packages
      snap:
        name:
          - postman
          - discord
          - dbeaver-ce
          - redisinsight

    - name: Check if VSCode is installed
      command: which code
      register: vscode_check
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Install VSCode if not present
      when: vscode_check.rc != 0
      block:
        - name: Download VSCode package
          get_url:
            url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
            dest: /tmp/vscode.deb
            mode: '0644'
        - name: Install VSCode
          apt:
            deb: /tmp/vscode.deb

    - name: Check if Google Chrome is installed
      command: which google-chrome
      register: chrome_check
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Install Google Chrome if not present
      when: chrome_check.rc != 0
      block:
        - name: Download Google Chrome package
          get_url:
            url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dest: /tmp/chrome.deb
            mode: '0644'
        - name: Install Google Chrome
          apt:
            deb: /tmp/chrome.deb

    - name: Check if Helm is installed
      command: which helm
      register: helm_check
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Install Helm if not present
      when: helm_check.rc != 0
      block:
        - name: Download Helm install script
          get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /tmp/get_helm.sh
            mode: '0700'
        - name: Install Helm
          command: /tmp/get_helm.sh
          environment:
            HOME: '{{ userhome }}'
            USER: '{{ username }}'
