---
- name: Install APT package on localhost
  hosts: localhost
  become: true

  vars_prompt:
    - name: git_email
      prompt: 'Enter your Git email'
      private: false

  vars:
    username: '{{ ansible_env.SUDO_USER | default(ansible_user_id) }}'
    userhome: "{{ '/root' if username == 'root' else '/home/' + username }}"
    fonts_dir: '{{ userhome }}/.local/share/fonts'

  roles:
    - docker
    - git
    - kubectl
    - nvm
    - ssh
    - zsh

  handlers:
    - name: Display setup summary
      ansible.builtin.debug:
        msg: |
          Setup completed successfully!
          User: {{ username }}
          Home: {{ userhome }}
          Fonts installed in: {{ fonts_dir }}

  tasks:
    - name: Install essential packages
      ansible.builtin.apt:
        state: present
        name:
          - vim
          - python3-pip
          - tree
          - ansible-lint

    - name: Install snap packages
      community.general.snap:
        name:
          - postman
          - discord
          - dbeaver-ce
          - redisinsight

    - name: Install VSCode if not present
      block:
        - name: Download VSCode package
          ansible.builtin.get_url:
            url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
            dest: /tmp/vscode.deb
            mode: '0644'
            timeout: 30
          retries: 3
        - name: Install VSCode
          ansible.builtin.apt:
            deb: /tmp/vscode.deb

    - name: Install Google Chrome if not present
      block:
        - name: Download Google Chrome package
          ansible.builtin.get_url:
            url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dest: /tmp/chrome.deb
            mode: '0644'
            timeout: 30
          retries: 3
        - name: Install Google Chrome
          ansible.builtin.apt:
            deb: /tmp/chrome.deb

    - name: Install Helm if not present
      block:
        - name: Download Helm install script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /tmp/get_helm.sh
            mode: '0700'
            timeout: 30
          retries: 3
        - name: Install Helm
          ansible.builtin.command: /tmp/get_helm.sh
          environment:
            HOME: '{{ userhome }}'
            USER: '{{ username }}'
          args:
            creates: /usr/local/bin/helm

    - name: Install 1Password if not present
      block:
        - name: Download 1Password package
          ansible.builtin.get_url:
            url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
            dest: /tmp/1password.deb
            mode: '0644'
            timeout: 30
          retries: 3

        - name: Install 1Password
          ansible.builtin.apt:
            deb: /tmp/1password.deb
