---
- name: Essentials
  hosts: k3s
  gather_facts: true
  become: true
  vars:
    vm_default_user: 'ubuntu'
    vm_default_password: 'ubuntu'
  roles:
    - prerequisite

- name: K3s Server Setup
  hosts: k8s-0
  gather_facts: true
  become: true
  vars:
    vm_default_user: 'ubuntu'
    vm_default_password: 'ubuntu'
    api_endpoint: "{{ hostvars['k8s-0']['ansible_host'] }}"
  roles:
    - k3s-server
