---
- name: Install and Configure KVM on Localhost
  hosts: localhost
  become: true
  vars:
    username: '{{ ansible_env.SUDO_USER | default(ansible_user_id) }}'
    userhome: "{{ '/root' if username == 'root' else '/home/' + username }}"
    ethernet_interface: "{{ bridge_interface | default('enp5s0') }}"
    bridge_name: br0
    bridge_connection_name: bridge-br0
    bridge_xml_file: /tmp/br0.xml
    iso_storage_path: '/var/lib/libvirt/images'
    ubuntu_cloud_image_filename: 'ubuntu-24.04-server-cloudimg-amd64.img'
    ubuntu_cloud_image_url: 'https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img'

    # Cloud-init defaults for automated VM provisioning
    cloudinit_template_dir: '/var/lib/libvirt/cloud-init-templates'
    vm_default_user: 'ubuntu'
    vm_default_password: 'ubuntu'
    vm_ssh_key_path: '{{ userhome }}/.ssh/id_ed25519.pub'
    vm_timezone: 'UTC'
    vm_templates:
      - { hostname: k8s-0, instance_id: 52:54:00:23:d7:b3 }
      - { hostname: k8s-1, instance_id: 52:54:00:86:c6:f1 }
      - { hostname: k8s-2, instance_id: 52:54:00:1e:d6:a9 }
    vm_memory: 8192
    vm_vcpus: 4
    vm_disk_size: 80

  handlers:
    - name: Display Ubuntu download complete
      ansible.builtin.debug:
        msg: |-
          Ubuntu ISO downloaded!
          Location: {{ iso_storage_path }}/{{ ubuntu_cloud_image_filename }}

  tasks:
    - name: Update APT cache and upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install KVM and virtualization dependencies
      ansible.builtin.apt:
        state: present
        name:
          - genisoimage
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - python3-pip
          - python3-libvirt
          - python3-lxml
          - whois
          - nmap
          - virt-manager
          - cloud-utils

    - name: Add user to libvirt group for virtualization access
      ansible.builtin.user:
        name: '{{ username }}'
        groups: libvirt
        append: true

    - name: Create bridge connection
      community.general.nmcli:
        conn_name: '{{ bridge_connection_name }}'
        ifname: '{{ bridge_name }}'
        type: bridge
        method4: auto
        state: present

    - name: Add ethernet interface to bridge as slave
      community.general.nmcli:
        conn_name: 'bridge-slave-{{ ethernet_interface }}'
        ifname: '{{ ethernet_interface }}'
        type: ethernet
        slave_type: bridge
        master: '{{ bridge_name }}'
        state: present

    - name: Activate bridge connection
      community.general.nmcli:
        conn_name: '{{ bridge_connection_name }}'
        state: up
      changed_when: false

    - name: Activate bridge slave connection
      community.general.nmcli:
        conn_name: 'bridge-slave-{{ ethernet_interface }}'
        state: up
      changed_when: false

    - name: Create libvirt definition for the bridge
      ansible.builtin.copy:
        dest: '{{ bridge_xml_file }}'
        content: |
          <network>
            <name>{{ bridge_name }}</name>
            <forward mode='bridge'/>
            <bridge name='{{ bridge_name }}'/>
          </network>
        owner: '{{ username }}'
        group: libvirt
        mode: '0664'

    - name: Define libvirt bridge network
      community.libvirt.virt_net:
        name: '{{ bridge_name }}'
        command: define
        xml: "{{ lookup('file', '{{bridge_xml_file}}') }}"

    - name: Start libvirt bridge network
      community.libvirt.virt_net:
        name: '{{ bridge_name }}'
        command: start

    - name: Set libvirt bridge network to autostart
      community.libvirt.virt_net:
        name: '{{ bridge_name }}'
        autostart: true

    - name: Create ISO storage directory
      ansible.builtin.file:
        path: '{{ iso_storage_path }}'
        state: directory
        owner: '{{ username }}'
        group: libvirt
        mode: '0775'

    - name: Create fresh cloud-init templates directory
      ansible.builtin.file:
        path: '{{ cloudinit_template_dir }}'
        state: directory
        owner: '{{ username }}'
        group: libvirt
        mode: '0775'

    - name: Read SSH public key
      tags: cloud-init
      ansible.builtin.slurp:
        src: '{{ vm_ssh_key_path }}'
      register: ssh_public_key

    - name: Download Ubuntu 24.04 Cloud Image
      ansible.builtin.get_url:
        url: '{{ ubuntu_cloud_image_url }}'
        dest: '{{ iso_storage_path }}/{{ ubuntu_cloud_image_filename }}'
        owner: '{{ username }}'
        group: libvirt
        mode: '0664'
        timeout: 1800
        force: false
      retries: 3
      delay: 10
      notify: Display Ubuntu download complete

    - name: Generate password hash for cloud-init
      ansible.builtin.set_fact:
        password_hash: "{{ vm_default_password | password_hash('sha512') }}"

    - name: Create Cloud init user-data template
      tags: cloud-init
      ansible.builtin.copy:
        dest: '{{ cloudinit_template_dir }}/user-data-{{ item.hostname }}.yaml'
        owner: '{{ username }}'
        group: libvirt
        mode: '0664'
        content: |
          #cloud-config
          fqdn: {{ item.hostname }}.k8s.internal
          hostname: {{ item.hostname }}
          manage_etc_hosts: true
          users:
            - name: ubuntu
              ssh-authorized-keys:
                - {{ lookup('file', vm_ssh_key_path) }}
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              groups: sudo
              shell: /bin/bash
              lock_passwd: false
              chpasswd: { expire: False }
              passwd: {{ password_hash }}
          ssh_pwauth: true
          package_update: true
          packages:
          - qemu-guest-agent
          - curl
          - git
          runcmd:
            - systemctl enable qemu-guest-agent
            - systemctl start qemu-guest-agent
      loop: '{{ vm_templates }}'

    - name: Create cloud-init meta-data template
      tags: cloud-init
      ansible.builtin.copy:
        dest: '{{ cloudinit_template_dir }}/meta-data-{{ item.hostname }}.yaml'
        content: |
          instance-id: {{ item.instance_id }}
          local-hostname: {{ item.hostname }}
        owner: '{{ username }}'
        group: libvirt
        mode: '0664'
      loop: '{{ vm_templates }}'

    - name: Create network-config file for each VM
      tags: cloud-init
      ansible.builtin.copy:
        dest: '{{ cloudinit_template_dir }}/network-config-{{ item.hostname }}.yaml'
        owner: '{{ username }}'
        group: '{{ username }}'
        mode: '0644'
        content: |
          version: 2
          ethernets:
            enp1s0:
              dhcp4: false
              addresses:
                - "{{ hostvars[item.hostname]['ansible_host'] }}/24"
              routes:
                - to: default
                  via: {{ ansible_default_ipv4.gateway }}
              nameservers:
                addresses: [8.8.8.8, 1.1.1.1]
      loop: '{{ vm_templates }}'

    - name: Create cloud-init ISO for each VM
      tags: cloud-init
      ansible.builtin.shell: |
        cloud-localds --network-config={{ cloudinit_template_dir }}/network-config-{{ item.hostname }}.yaml \
        {{ cloudinit_template_dir }}/cloud-init-{{ item.hostname }}.iso \
        {{ cloudinit_template_dir }}/user-data-{{ item.hostname }}.yaml \
        {{ cloudinit_template_dir }}/meta-data-{{ item.hostname }}.yaml
      become_user: '{{ username }}'
      loop: '{{ vm_templates }}'
      args:
        creates: '{{ cloudinit_template_dir }}/cloud-init-{{ item.hostname }}.iso'

    - name: Set ownership of cloud-init ISO files
      ansible.builtin.file:
        path: '{{ cloudinit_template_dir }}/cloud-init-{{ item.hostname }}.iso'
        owner: '{{ username }}'
        group: libvirt
        mode: '0664'
      loop: '{{ vm_templates }}'

    - name: Create VM disk images with Ubuntu cloud image backing
      tags: vm-create
      ansible.builtin.shell: |
        qemu-img create -f qcow2 \
        -o backing_file={{ iso_storage_path }}/{{ ubuntu_cloud_image_filename }},backing_fmt=qcow2 \
        {{ iso_storage_path }}/{{ item.hostname }}.qcow2 {{ vm_disk_size }}G
      become_user: '{{ username }}'
      loop: '{{ vm_templates }}'
      args:
        creates: '{{ iso_storage_path }}/{{ item.hostname }}.qcow2'

    - name: Set ownership of VM disk images
      ansible.builtin.file:
        path: '{{ iso_storage_path }}/{{ item.hostname }}.qcow2'
        owner: '{{ username }}'
        group: libvirt
        mode: '0664'
      loop: '{{ vm_templates }}'

    - name: Create VMs with virt-install
      tags: vm-create
      ansible.builtin.shell: |
        virt-install \
        --name {{ item.hostname }} \
        --ram {{ vm_memory }} \
        --vcpus {{ vm_vcpus }} \
        --disk path={{ iso_storage_path }}/{{ item.hostname }}.qcow2,format=qcow2 \
        --cdrom {{ cloudinit_template_dir }}/cloud-init-{{ item.hostname }}.iso \
        --network network={{ bridge_name }},mac={{ item.instance_id }} \
        --os-type linux \
        --os-variant ubuntu24.04 \
        --graphics none \
        --noautoconsole \
        --import
      loop: '{{ vm_templates }}'
      args:
        creates: /etc/libvirt/qemu/{{ item.hostname }}.xml

    - name: Enable autostart for VMs
      tags: vm-create
      community.libvirt.virt:
        name: '{{ item.hostname }}'
        autostart: true
      loop: '{{ vm_templates }}'

    - name: Display connection info
      ansible.builtin.debug:
        msg: |
          {{ vm_templates | length }} VMs created with cloud-init auto-provisioning!

          VMs: {{ vm_templates | map(attribute='hostname') | join(', ') }}

          Cloud-init will configure each VM on first boot with:
          - Your SSH key for passwordless access
          - Default user: {{ vm_default_user }}
          - Automatic package updates
          - Common development tools (qemu-guest-agent, curl, git)

          Wait 2-3 minutes for cloud-init to complete, then:
          - SSH: ssh {{ vm_default_user }}@<vm-ip>
          - Console: virsh console <vm-name>
          - GUI: Launch virt-manager

          Commands:
          - List VMs: virsh list --all
          - Get VM IPs: virsh domifaddr <vm-name> --source agent
          - VM info: virsh dominfo <vm-name>
          - Launch GUI: virt-manager
          - Check autostart: virsh dominfo <vm-name> | grep Autostart

          Expected FQDN format: <hostname>.k8s.internal
          Bridge network: {{ bridge_name }}
          SSH key: {{ vm_ssh_key_path }}
          VM Autostart: ENABLED

          Storage locations:
          - VM Images: {{ iso_storage_path }}
          - Cloud-init templates: {{ cloudinit_template_dir }}
          - All files owned by: {{ username }}:libvirt
